config-version: 2

name: 'asana'
version: '0.0.1'

require-dbt-version: '>=0.17.0'

models:
    asana:
        materialized: table
        intermediate:
            materialized: ephemeral 

vars:
    asana: 
        project_task: "{{ ref('stg_asana_project_task') }}"
        project: "{{ ref('stg_asana_project') }}"
        section: "{{ ref('stg_asana_section') }}"
        story: "{{ ref('stg_asana_story') }}"
        tag: "{{ ref('stg_asana_tag') }}"
        task_follower: "{{ ref('stg_asana_task_follower') }}"
        task_section: "{{ ref('stg_asana_task_section') }}"
        task_tag: "{{ ref('stg_asana_task_tag') }}"
        task: "{{ ref('stg_asana_task') }}"
        team: "{{ ref('stg_asana_team') }}"
        user: "{{ ref('stg_asana_user') }}"

profile: dev_bigquery_dbt_testing